### ISSUE TITLE
Version 1.0 in forms

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-dp-frontend#127]
Not so much a portal issue itself but the title on the contact form displayed in https://forms.office.com/pages/responsepage.aspx?id=AcQ6OB2ia0KAcl90w2twk7fwO2KG6sVNroEUPM3X2sJUQ0g1SkY3WkQ0TTBHTU9QNThSMEhSN0VLUCQlQCN0PWcu (and reachable through the "connect" link on the landing page) reads "EJP RD Virtual Platform (Version 1.0) " - that should be 1.6 now (or completley removed)

**Comment by vabishaa** [comment]
@kkr-ait: I removed the version. Please check it again and close the issue if it is solved. Thanks.
