### ISSUE TITLE
No record-level results for 730 (kidney disease)

### ISSUE THREAD

**Issue by kkr-ait** [ejp-rd-vp/vp-dp-frontend#130]
I am logged in and search orphacode 730 (a kidney disease) - V1.5 of the portal that is in production has record-level results (from ERKREG) - V1.6 on development does not show any results.

**Comment by kkr-ait** [comment]
I am pretty sure that ERKREG should appear on record level

**Comment by vabishaa** [comment]
> I am pretty sure that ERKREG should appear on record level

the endpoint is working, however the Portal is not retrieving the endpoint url information, which could be an issue in providing the metadata

**Comment by kkr-ait** [comment]
Closing this - as this is not a portal problem as discussed.
